
name: CI Pipeline Dragon Ball App Test Main

on:
  push:
    branches:
      - main # Actualiza a la rama principal
      - develop
      - project_base

jobs:
    runs-on: ubuntu-latest # Actualiza a la última versión de Ubuntu

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.17.0'

    - name: Install dependencies
      run: npm install 

  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}


    - name: Run build
      run: npm run build

    - name: Export static site
      run: npm run export

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.17.0'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Export static site
      run: npm run export

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        publish_dir: ./out